### ISSUE TITLE
Add a link to this repo in the footer

### ISSUE THREAD

**Issue by ibnesayeed** [oduwsdl/tmvis#79]
Currently, the service at http://tmvis.ws-dl.cs.odu.edu/ does not point back to this repo. I think it will be good to include a link in the footer so people can discover the repo easily.

**Comment by phonedude** [comment]
this is a good idea

@a-mabe @dhruv282 @weiglemc

**Comment by machawk1** [comment]
Closing via 81d51c114ea3d867a39144cccaaa589513138b0d from @a-mabe
